name: task_management_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_riverpod: ^3.0.3
  google_fonts: ^6.3.2
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
